### PR TITLE
Reunify forks

### PR DESCRIPTION
**Pull request by ieure**
This PR unifies the fork of test-case-mode that I've been maintaining for many years with your changes from a couple years ago.

I had initially tried to reach out to contribute back to TCM, but when I got no response, I took on maintaining it, adding backends, TRAMP support, better detection of the directory to run tests in, releasing to Marmalade, etc. I just want to say thank you for writing it initially, I've been using it for years, and it remains one of the best dev tools for Emacs.

Because there's a multi-year divergence, there were numerous conflicts, and the diff isn't always the easiest to read. I'm happy to resolve issues that arise from this.

### CODE REVIEW

**Comment by nschum** [comment]
Thanks for working on this. Would you like to officially take over as maintainer? You seem to be doing a better job than me.

**Comment by ieure** [comment]
Sure!

**Comment by nschum** [comment]
I've given you push access, but I'd like to transfer the repo to you, so everything is properly forwarded and yours doesn't look like a fork anymore.

But you need to remove your repository with the same name first, otherwise github won't let me transfer it.

**Comment by ieure** [comment]
Thanks, I renamed my fork, so you should be able to transfer now.

**Comment by nschum** [comment]
Nope, that wasn't enough: "ieure already has a repository in the nschum/test-case-mode network"

**Comment by ieure** [comment]
Okay, deleted my fork.

**Comment by nschum** [comment]
Transfer waiting to be accepted.

**Comment by ieure** [comment]
I don't see anywhere I can accept the transfer. Perhaps it times out?

**Pull request closed without merging**
